spring.datasource.url=jdbc:postgresql://localhost:5432/task_management_db
spring.datasource.username=remont
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080